baseURL = "https://fbenevides.io/"
languageCode = "en-us"
title = "Frederico Benevides"
theme = "mytheme"

enableRobotsTXT = true

[menu]

  [[menu.main]]
    name = "home"
    url = "#home"
    weight = 1

  [[menu.main]]
    name = "about"
    url = "#about"
    weight = 2

  [[menu.main]]
    name = "contact"
    url = "#contact"
    weight = 3

[params]
  linkedin = "linkedin.com/in/fredericobenevides"
  linkedinUrl = "https://www.linkedin.com/in/fredericobenevides"

  github = "github.com/fredericobenevides"
  githubUrl = "https://github.com/fredericobenevides"

  email = "me@fbenevides.io"

  gtag = "G-712RT362ZG"
