baseURL = "https://fredericobenevides.com/"
languageCode = "en-us"
title = "Frederico Benevides"
theme = "mytheme"

[menu]

  [[menu.main]]
    name = "home"
    url = "#home"
    weight = 1

  [[menu.main]]
    name = "about"
    url = "#about"
    weight = 2

  [[menu.main]]
    name = "contact"
    url = "#contact"
    weight = 3

[params]
  linkedin = "https://www.linkedin.com/in/fredericobenevides"
  github = "https://github.com/fredericobenevides"
  email = "contato@fredericobenevides.com"

  gtag = "G-712RT362ZG"
